### ISSUE TITLE
弹出的权限设置页面不对

### ISSUE THREAD

**Issue by crazywenza** [zhoulinxue/BGStart#1]
![image](https://user-images.githubusercontent.com/5308791/87782728-a55fea00-c865-11ea-93bc-6a72a6c8842b.png)
应该是打开 后台启动权限的开关设置页面

**Comment by zhoulinxue** [comment]
好的  谢谢你的issue   后台启动权限   并不是 标准权限 各个room 不一定有  目前发现  小米 手机有这个权限 但是没找到 资料 怎么去跳转   小米 品牌 各个机型  针对这个权限 适配也 不一样  目前 小米 手机  最优解决方案  是 【后台启动】和【悬浮窗】两个权限都开。方便的话 请 留个 设备信息 我尽量 适配 谢谢您！！！
